# Generated by Django 4.0.3 on 2022-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchCardNo', models.CharField(max_length=30)),
                ('Brand_Name', models.CharField(max_length=30)),
                ('Brand_No', models.CharField(max_length=30)),
                ('Batch_Size', models.IntegerField()),
                ('THBatch_Size', models.IntegerField()),
                ('SAP_Code', models.CharField(max_length=30)),
                ('Chemical_name', models.CharField(max_length=100)),
                ('Product_Category', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=30)),
                ('Expiry', models.IntegerField()),
                ('Expiry_Date', models.CharField(max_length=30)),
                ('Tank_Num', models.CharField(max_length=30)),
                ('Remark', models.CharField(max_length=100)),
                ('Technicals', models.CharField(max_length=500)),
                ('Raw_Materials', models.CharField(max_length=1000)),
                ('BatchCard_Approval', models.CharField(default='Pending', max_length=30)),
                ('BatchCard_Status', models.CharField(default='Pending', max_length=30)),
                ('AllotedOperator', models.CharField(default='Not Alloted', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=30)),
                ('Brand_No', models.CharField(max_length=30)),
                ('SAP_Code', models.CharField(max_length=30)),
                ('SPGR', models.FloatField(default=0)),
                ('Chemical_name', models.CharField(max_length=100)),
                ('Raw_Materials', models.CharField(max_length=1000)),
                ('Technicals', models.CharField(max_length=500)),
                ('product_category', models.CharField(max_length=30)),
                ('expiry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Line_Incharge_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_cards_one', models.BooleanField()),
                ('batch_cards_two', models.BooleanField()),
                ('tasks_one', models.BooleanField()),
                ('tasks_two', models.BooleanField()),
                ('maintenance_one', models.BooleanField()),
                ('maintenance_two', models.BooleanField()),
                ('sops_one', models.BooleanField()),
                ('sops_two', models.BooleanField()),
                ('alarms_one', models.BooleanField()),
                ('alarms_two', models.BooleanField()),
                ('profiles_one', models.BooleanField()),
                ('profiles_two', models.BooleanField()),
                ('mp_plan_one', models.BooleanField()),
                ('mp_plan_two', models.BooleanField()),
                ('prod_plan_one', models.BooleanField()),
                ('prod_plan_two', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_cards_one', models.BooleanField()),
                ('batch_cards_two', models.BooleanField()),
                ('tasks_one', models.BooleanField()),
                ('tasks_two', models.BooleanField()),
                ('maintenance_one', models.BooleanField()),
                ('maintenance_two', models.BooleanField()),
                ('sops_one', models.BooleanField()),
                ('sops_two', models.BooleanField()),
                ('alarms_one', models.BooleanField()),
                ('alarms_two', models.BooleanField()),
                ('profiles_one', models.BooleanField()),
                ('profiles_two', models.BooleanField()),
                ('mp_plan_one', models.BooleanField()),
                ('mp_plan_two', models.BooleanField()),
                ('prod_plan_one', models.BooleanField()),
                ('prod_paln_two', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Incharge_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_cards_one', models.BooleanField()),
                ('batch_cards_two', models.BooleanField()),
                ('tasks_one', models.BooleanField()),
                ('tasks_two', models.BooleanField()),
                ('maintenance_one', models.BooleanField()),
                ('maintenance_two', models.BooleanField()),
                ('sops_one', models.BooleanField()),
                ('sops_two', models.BooleanField()),
                ('alarms_one', models.BooleanField()),
                ('alarms_two', models.BooleanField()),
                ('profiles_one', models.BooleanField()),
                ('profiles_two', models.BooleanField()),
                ('mp_plan_one', models.BooleanField()),
                ('mp_plan_two', models.BooleanField()),
                ('prod_plan_one', models.BooleanField()),
                ('prod_paln_two', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('sop_category', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('User_Role', models.CharField(max_length=30)),
                ('Shift', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('plant_name', models.CharField(max_length=30)),
                ('line_name', models.CharField(max_length=30)),
            ],
        ),
    ]
