# Generated by Django 4.0.3 on 2022-04-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0002_alter_chemical_raw_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='Raw_Materials',
            field=models.CharField(max_length=5000),
        ),
    ]
