# Generated by Django 4.0.3 on 2022-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0003_alter_chemical_raw_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_card',
            name='MFG_Date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch_card',
            name='ShiftName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
