# Generated by Django 4.0.3 on 2022-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0005_alter_chemical_raw_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_card',
            name='Raw_Materials',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='batch_card',
            name='Technicals',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='Raw_Materials',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='Technicals',
            field=models.TextField(max_length=500),
        ),
    ]
