# Generated by Django 4.0.3 on 2022-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0006_alter_batch_card_raw_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_card',
            name='SPGR',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
