# Generated by Django 4.0.3 on 2022-04-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0007_batch_card_spgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_card',
            name='Add_Chemical',
            field=models.TextField(default=[], max_length=10000),
            preserve_default=False,
        ),
    ]
