# Generated by Django 4.0.3 on 2022-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0009_addchemical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addchemical',
            name='DateTime',
            field=models.CharField(max_length=30),
        ),
    ]
