# Generated by Django 4.0.3 on 2022-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0010_alter_addchemical_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addchemical',
            name='LoadCellEnd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addchemical',
            name='LoadCellReading',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addchemical',
            name='LoadCellStart',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addchemical',
            name='Percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addchemical',
            name='QuantityAdded',
            field=models.IntegerField(),
        ),
    ]
