# Generated by Django 4.0.3 on 2022-04-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0011_alter_addchemical_loadcellend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddChemical',
        ),
    ]
