# Generated by Django 4.0.3 on 2022-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0012_delete_addchemical'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=50)),
                ('assigned', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(max_length=1000)),
            ],
        ),
    ]
