# Generated by Django 4.0.3 on 2022-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0013_createtask_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='activity',
            new_name='Maintenance',
        ),
        migrations.AddField(
            model_name='task',
            name='Production',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
