# Generated by Django 4.0.3 on 2022-04-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0014_rename_activity_task_maintenance_task_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Maintenance',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Production',
        ),
        migrations.AddField(
            model_name='task',
            name='Activity',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
