# Generated by Django 4.0.3 on 2022-04-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0015_remove_task_maintenance_remove_task_production_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks_list',
        ),
        migrations.RenameField(
            model_name='tasks_list',
            old_name='Activity',
            new_name='Tasks',
        ),
    ]
