# Generated by Django 4.0.3 on 2022-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0017_rename_date_createtask_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='status',
            field=models.CharField(default='InProgress', max_length=50),
        ),
    ]
