# Generated by Django 4.0.3 on 2022-04-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0019_alter_createtask_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManPower_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.CharField(max_length=30)),
                ('AllotedDate', models.CharField(max_length=30)),
                ('shift', models.CharField(max_length=30)),
                ('contractor', models.CharField(max_length=30)),
                ('allotment', models.CharField(max_length=30)),
                ('noofalotment', models.CharField(max_length=30)),
                ('plant', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlantName', models.CharField(max_length=100)),
                ('ContractorDetails', models.CharField(max_length=100)),
                ('AllotmentDetails', models.CharField(max_length=100)),
            ],
        ),
    ]
