# Generated by Django 4.0.3 on 2022-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0021_rename_alloteddate_manpower_detail_allotteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_detail',
            name='LineDetails',
            field=models.CharField(default=[], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant_detail',
            name='MachineDetails',
            field=models.CharField(default=[''], max_length=100),
            preserve_default=False,
        ),
    ]
