# Generated by Django 4.0.3 on 2022-04-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0022_plant_detail_linedetails_plant_detail_machinedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatetime', models.CharField(max_length=30)),
                ('maintenancetype', models.CharField(max_length=30)),
                ('plant', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=30)),
                ('machine', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('part', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=30)),
                ('enddatetime', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=30)),
            ],
        ),
    ]
