# Generated by Django 4.0.3 on 2022-04-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0024_maintenance_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_card',
            name='SPGR',
            field=models.FloatField(),
        ),
    ]
