# Generated by Django 4.0.3 on 2022-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0025_alter_batch_card_spgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='created_date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
