# Generated by Django 4.0.3 on 2022-04-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0026_sop_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop',
            name='file',
            field=models.FileField(upload_to='documents'),
        ),
    ]
