# Generated by Django 4.0.3 on 2022-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0030_batch_card_add_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_types', models.CharField(max_length=30)),
            ],
        ),
    ]
