# Generated by Django 4.0.3 on 2022-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0031_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchCardNo', models.CharField(max_length=30)),
                ('PackageCardNo', models.CharField(max_length=30)),
                ('ShiftName', models.CharField(max_length=20)),
                ('LineName', models.CharField(max_length=30)),
                ('Created_Date', models.CharField(max_length=30)),
                ('Chemical_name', models.CharField(max_length=100)),
                ('SPGR', models.FloatField()),
                ('Packsize', models.IntegerField()),
                ('MaterialNetWt', models.FloatField()),
                ('ContainerWt', models.FloatField()),
                ('GrossWt', models.FloatField()),
                ('CapAvgWt', models.FloatField()),
                ('StdWt', models.FloatField()),
                ('MinStdWt', models.FloatField()),
                ('MacPercent', models.FloatField()),
                ('MaxStdWt', models.FloatField()),
                ('Remark', models.CharField(max_length=200)),
                ('Instructions', models.CharField(max_length=200)),
                ('PackageCardApproval', models.CharField(max_length=30)),
                ('PackageCardStatus', models.CharField(max_length=30)),
            ],
        ),
    ]
