# Generated by Django 4.0.3 on 2022-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0032_packagecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecard',
            name='PackageCardApproval',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='PackageCardStatus',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
