# Generated by Django 4.0.3 on 2022-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0033_alter_packagecard_packagecardapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecard',
            name='MinPercent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='CapAvgWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='ContainerWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='GrossWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='MacPercent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='MaterialNetWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='MaxStdWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='MinStdWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='Packsize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='SPGR',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagecard',
            name='StdWt',
            field=models.FloatField(default=0.0),
        ),
    ]
