# Generated by Django 4.0.3 on 2022-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0035_alter_batch_card_add_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecard',
            name='Created_By',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='machine_speed',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='nozzle_five',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='nozzle_four',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='nozzle_one',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='nozzle_six',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='nozzle_three',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='nozzle_two',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
