# Generated by Django 4.0.3 on 2022-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0036_packagecard_created_by_packagecard_machine_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecard',
            name='add_package',
            field=models.TextField(default=[], max_length=1000),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='bottle_tetsing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='induction_sealing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='leakage_testing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='plugging',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='sleeve_packing',
            field=models.IntegerField(default=0),
        ),
    ]
