# Generated by Django 4.0.3 on 2022-05-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0037_packagecard_add_package_packagecard_bottle_tetsing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagecard',
            old_name='bottle_tetsing',
            new_name='bottle_testing',
        ),
    ]
