# Generated by Django 4.0.3 on 2022-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0040_batch_card_base_calc_alter_batch_card_add_chemical_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagecard',
            old_name='Brand_name',
            new_name='Chemical_name',
        ),
        migrations.AlterField(
            model_name='batch_card',
            name='Base_Calc',
            field=models.CharField(default='Batch_Size', max_length=30),
        ),
    ]
