# Generated by Django 4.0.3 on 2022-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0041_rename_brand_name_packagecard_chemical_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation_operator', models.TextField(max_length=5000)),
                ('packaging_operator', models.TextField(max_length=5000)),
                ('formulation_shiftincharge', models.TextField(max_length=5000)),
                ('packaging_shiftincharge', models.TextField(max_length=5000)),
                ('formulation_lineincharge', models.TextField(max_length=5000)),
                ('packaging_lineincharge', models.TextField(max_length=5000)),
                ('admin', models.TextField(default=[], max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='createtask',
            name='created_by',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance_detail',
            name='created_by',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecard',
            name='BoxType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='Plant_Name',
            field=models.CharField(default='Herbicide', max_length=30),
        ),
        migrations.AddField(
            model_name='packagecard',
            name='Units_Box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_data',
            name='process',
            field=models.CharField(default='Formulation', max_length=30),
        ),
    ]
