# Generated by Django 4.0.3 on 2022-09-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0042_notifications_db_createtask_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_db',
            name='formulation_lineincharge',
            field=models.TextField(default=[], max_length=5000),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='formulation_operator',
            field=models.TextField(default=[], max_length=5000),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='formulation_shiftincharge',
            field=models.TextField(default=[], max_length=5000),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='packaging_lineincharge',
            field=models.TextField(default=[], max_length=5000),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='packaging_operator',
            field=models.TextField(default=[], max_length=5000),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='packaging_shiftincharge',
            field=models.TextField(default=[], max_length=5000),
        ),
    ]
