# Generated by Django 4.0.3 on 2022-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0043_alter_notifications_db_formulation_lineincharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_db',
            name='admin',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='formulation_lineincharge',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='formulation_operator',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='formulation_shiftincharge',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='packaging_lineincharge',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='packaging_operator',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='notifications_db',
            name='packaging_shiftincharge',
            field=models.TextField(default=[]),
        ),
    ]
