# Generated by Django 4.0.3 on 2023-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adama_app', '0046_rename_nozzle_one_packagecard_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecard',
            name='BoxType',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
